import random
loop = "y"
score = 0
game = 1
credits = 1

while loop == "y":


    if credits == 0:
        game = 1
        credits = 1
    print("**************************************************")
    print("!*!*!     !*!*!     NUMB0RAND0     !*!*!     !*!*!")
    print("**************************************************")
    print("Guess the random number generated by the computer.")
    print()
    while True:
        print("Game: |" + str(game) + "|")
        print("Score: |" + str(score) + "|")
        print("Credits: |" + str(credits) + "|")
        diff = input("Insert credit(s) to play: ")


        if diff.isdigit():

            diff = int(diff)



            if diff > credits:
                print("You don't have that many credits!")

                print()
                continue
            elif diff <= 0:
                print("Enter  a number greater than zero!")

                print()
                continue
        else:
            print("This isn't a number!")
            print()
            continue
        print("Inserted " + str(diff) + " credit(s).")


        diff = (diff * 10)
        #top = (diff * 10)
        given = (diff // 2)
        random_num = random.randint(1, diff)


        credits = given + credits - 1

        print()
        print("+" + str(given) + " credit(s) received.")
        print("|" + str(credits) + "|credit(s) remaining.")
        random_num = random.randint(1, diff)
        print("Please note: Credits will decrease by 1 with every guess.")
        print("")
        break


    while True:

        print()
        guess = input("Guess the Numb0Rand0 (1 - " + str(diff) + "): ")


        if guess.isdigit():
            guess = int(guess)
            if guess <= 0:
                print("I said between 0 - " + str(diff))
                credits = credits - 1
                if credits == 0:
                    print("|GAMEOVER| You ran out of credits.")
                    print("The Numb0Rand0 was " + str(random_num) + ".")
                    loop = input("Would you like to play again? (Y or N) ")
                    print()
                    break

                if credits == 1:
                    print("|" + str(credits) + "|credit remaining. ")
                    print()
                else:
                    print("|" + str(credits) + "|credits remaining. ")
                    print()
                    continue
                continue
            if guess > diff:
                print("It has to be less than " + str(diff))
                credits = credits - 1
                if credits == 0:
                    print("|GAMEOVER| You ran out of credits.")
                    print("The Numb0Rand0 was " + str(random_num) + ".")
                    loop = input("Would you like to play again? (Y or N) ")
                    print()
                    break


                if credits == 1:
                    print("|" + str(credits) + "|credit remaining. ")
                    print()
                else:
                    print("|" + str(credits) + "|credits remaining. ")
                    print()
                    continue
                continue
        else:
            print("Please enter a number")
            credits = credits - 1
            if credits == 0:
                print("|GAMEOVER| You ran out of credits.")
                print("The Numb0Rand0 was " + str(random_num) + ".")
                loop = input("Would you like to play again? (Y or N) ")
                print()
                break

            if credits == 1:
                print("|" + str(credits) + "|credit remaining. ")
                print()
            else:
                print("|" + str(credits) + "|credits remaining. ")
                print()
                continue
            continue
        if guess > random_num:
            print("***WRONG!  TOO HIGH***")
            credits = credits - 1
            if credits == 0:
                print()
                print("|GAMEOVER| You ran out of credits.")
                print("Game: |" + str(game) + "|")
                print("Final score: |" + str(score) + "|")
                print("The Numb0Rand0 was " + str(random_num) + ".")
                loop = input("Would you like to play again? (Y or N) ")
                print()
                break

            if credits == 1:
                print("|" + str(credits) + "|credit remaining. ")

            else:
                print("|" + str(credits) + "|credits remaining. ")

                continue
        elif guess < random_num:
            print("***WRONG! TOO LOW***")
            credits = credits - 1
            if credits <= 0:
                print()
                print("|GAMEOVER| You ran out of credits.")
                print("The Numb0Rand0 was " + str(random_num) + ".")
                print("Game: |" + str(game) + "|")
                print("Final score: |" + str(score) + "|")
                loop = input("Would you like to play again? (Y or N) ")
                print()
                break

            if credits == 1:
                print("|" + str(credits) + "|credit remaining. ")

            else:
                print("|" + str(credits) + "|credits remaining. ")

                continue
        else:
            score = score + diff * 33
            print()
            print("***YOU***WIN!***")
            print("Your score now is |" + str(score) + "|")
            print("Credit(s) remaining: |" + str(credits) + "|")
            print()
            loop = input("Would you like to play again? (Y or N) ")
            game = game + 1
            print()
            break
print("Ending game")


#numb0rand0 needs some tweaks. right now you enter the cap of the range of numbers. I would like
#to try and utilize the credits and score variables somehow. maybe you insert a number of credits
# and that determines the cap, the amount of spare credits received, and score at the end.

#also need to tweak some of the conclusion placements. I'm not seeing the statement of games played